app:
  debug: false
  name: Muzik
  version: 0.1.0
display:
  colors: true
  unicode: true
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
spotify:
  access_token: 'access_token'
  client_id: 'client_id'
  client_secret: 'client_secret'
  redirect_uri: 'http://localhost:8888/callback'
  refresh_token: 'refresh_token'
